kind: Service
apiVersion: v1
metadata:
  name: api-book
  labels:
    app: api-book
spec:
  type: NodePort
  selector:
    app: api-book
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-book
  template:
    metadata:
      labels:
        app: api-book
        version: v1
    spec:
      containers:
      - name: api-book
        image: api-book
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
